# Generated by Django 4.2.20 on 2025-04-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="challenge",
            field=models.FloatField(default=3.0),
        ),
    ]
