# Generated by Django 4.2.20 on 2025-04-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="challenge",
        ),
    ]
