# Generated by Django 4.2.16 on 2025-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_about_profile_image_alter_about_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
